schema_version: 1

context:
  name: libvalkey-py
  version: "4.1.0"

package:
  name: "${{ name }}"
  version: "${{ version }}"

source:
  url: https://files.pythonhosted.org/packages/source/l/libvalkey/libvalkey-${{ version }}.tar.gz
  sha256: "b88231e09600909723cd07949982cc7758298027d86504d948a223075f0022f4"

build:
  number: 1
  script:
    env:
      PIP_USE_PEP517: "1"
    content:
      - python -m pip install --no-build-isolation .

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - if: build_platform != target_platform
      then:
        - python
        - "cross-python_${{ target_platform }}"

  host:
    - python
    - setuptools
    - pip

  run:
    - python

tests:
  - python:
      imports:
        - libvalkey

about:
  license: MIT
  license_file:
    - LICENSE
  summary: Python extension that wraps protocol parsing code in libvalkey. It primarily speeds up parsing of multi bulk replies.
  description: |
    Python extension that wraps protocol parsing code in libvalkey.
    It primarily speeds up parsing of multi bulk replies.
  homepage: https://github.com/valkey-io/libvalkey-py
  repository: https://github.com/valkey-io/libvalkey-py

extra:
  recipe-maintainers:
    - trim21
